export interface StockInfo {
  ticker: string;
  name: string;
  sector: string;
}

export const POPULAR_STOCKS: StockInfo[] = [
  { ticker: 'AAPL', name: 'Apple Inc.', sector: 'Technology' },
  { ticker: 'MSFT', name: 'Microsoft Corporation', sector: 'Technology' },
  { ticker: 'GOOGL', name: 'Alphabet Inc.', sector: 'Technology' },
  { ticker: 'AMZN', name: 'Amazon.com Inc.', sector: 'Consumer Cyclical' },
  { ticker: 'TSLA', name: 'Tesla Inc.', sector: 'Consumer Cyclical' },
  { ticker: 'META', name: 'Meta Platforms Inc.', sector: 'Communication Services' },
  { ticker: 'NVDA', name: 'NVIDIA Corporation', sector: 'Technology' },
  { ticker: 'BRK.B', name: 'Berkshire Hathaway Inc.', sector: 'Financial Services' },
  { ticker: 'V', name: 'Visa Inc.', sector: 'Financial Services' },
  { ticker: 'JPM', name: 'JPMorgan Chase & Co.', sector: 'Financial Services' },
  { ticker: 'JNJ', name: 'Johnson & Johnson', sector: 'Healthcare' },
  { ticker: 'WMT', name: 'Walmart Inc.', sector: 'Consumer Defensive' },
  { ticker: 'PG', name: 'Procter & Gamble Co.', sector: 'Consumer Defensive' },
  { ticker: 'MA', name: 'Mastercard Inc.', sector: 'Financial Services' },
  { ticker: 'UNH', name: 'UnitedHealth Group Inc.', sector: 'Healthcare' },
  { ticker: 'HD', name: 'The Home Depot Inc.', sector: 'Consumer Cyclical' },
  { ticker: 'BAC', name: 'Bank of America Corp.', sector: 'Financial Services' },
  { ticker: 'DIS', name: 'The Walt Disney Company', sector: 'Communication Services' },
  { ticker: 'ADBE', name: 'Adobe Inc.', sector: 'Technology' },
  { ticker: 'NFLX', name: 'Netflix Inc.', sector: 'Communication Services' },
  { ticker: 'PYPL', name: 'PayPal Holdings Inc.', sector: 'Financial Services' },
  { ticker: 'INTC', name: 'Intel Corporation', sector: 'Technology' },
  { ticker: 'CMCSA', name: 'Comcast Corporation', sector: 'Communication Services' },
  { ticker: 'PEP', name: 'PepsiCo Inc.', sector: 'Consumer Defensive' },
  { ticker: 'KO', name: 'The Coca-Cola Company', sector: 'Consumer Defensive' },
  { ticker: 'CSCO', name: 'Cisco Systems Inc.', sector: 'Technology' },
  { ticker: 'AVGO', name: 'Broadcom Inc.', sector: 'Technology' },
  { ticker: 'TMO', name: 'Thermo Fisher Scientific Inc.', sector: 'Healthcare' },
  { ticker: 'COST', name: 'Costco Wholesale Corp.', sector: 'Consumer Defensive' },
  { ticker: 'ABT', name: 'Abbott Laboratories', sector: 'Healthcare' },
  { ticker: 'ORCL', name: 'Oracle Corporation', sector: 'Technology' },
  { ticker: 'CRM', name: 'Salesforce Inc.', sector: 'Technology' },
  { ticker: 'ACN', name: 'Accenture plc', sector: 'Technology' },
  { ticker: 'DHR', name: 'Danaher Corporation', sector: 'Healthcare' },
  { ticker: 'NKE', name: 'NIKE Inc.', sector: 'Consumer Cyclical' },
  { ticker: 'LIN', name: 'Linde plc', sector: 'Basic Materials' },
  { ticker: 'NEE', name: 'NextEra Energy Inc.', sector: 'Utilities' },
  { ticker: 'TXN', name: 'Texas Instruments Inc.', sector: 'Technology' },
  { ticker: 'PM', name: 'Philip Morris International Inc.', sector: 'Consumer Defensive' },
  { ticker: 'UPS', name: 'United Parcel Service Inc.', sector: 'Industrials' },
  { ticker: 'MS', name: 'Morgan Stanley', sector: 'Financial Services' },
  { ticker: 'RTX', name: 'Raytheon Technologies Corp.', sector: 'Industrials' },
  { ticker: 'HON', name: 'Honeywell International Inc.', sector: 'Industrials' },
  { ticker: 'WFC', name: 'Wells Fargo & Company', sector: 'Financial Services' },
  { ticker: 'AMD', name: 'Advanced Micro Devices Inc.', sector: 'Technology' },
  { ticker: 'QCOM', name: 'QUALCOMM Inc.', sector: 'Technology' },
  { ticker: 'IBM', name: 'IBM Corporation', sector: 'Technology' },
  { ticker: 'GS', name: 'The Goldman Sachs Group Inc.', sector: 'Financial Services' },
  { ticker: 'CAT', name: 'Caterpillar Inc.', sector: 'Industrials' },
  { ticker: 'DE', name: 'Deere & Company', sector: 'Industrials' },
  { ticker: 'BA', name: 'The Boeing Company', sector: 'Industrials' },
  { ticker: 'GE', name: 'General Electric Company', sector: 'Industrials' },
  { ticker: 'MMM', name: '3M Company', sector: 'Industrials' },
  { ticker: 'AXP', name: 'American Express Company', sector: 'Financial Services' },
  { ticker: 'CVX', name: 'Chevron Corporation', sector: 'Energy' },
  { ticker: 'COP', name: 'ConocoPhillips', sector: 'Energy' },
  { ticker: 'SLB', name: 'Schlumberger Limited', sector: 'Energy' },
  { ticker: 'PFE', name: 'Pfizer Inc.', sector: 'Healthcare' },
  { ticker: 'MRK', name: 'Merck & Co. Inc.', sector: 'Healthcare' },
  { ticker: 'ABBV', name: 'AbbVie Inc.', sector: 'Healthcare' },
  { ticker: 'BMY', name: 'Bristol-Myers Squibb Co.', sector: 'Healthcare' },
  { ticker: 'C', name: 'Citigroup Inc.', sector: 'Financial Services' },
  { ticker: 'SCHW', name: 'The Charles Schwab Corp.', sector: 'Financial Services' },
  { ticker: 'BLK', name: 'BlackRock Inc.', sector: 'Financial Services' },
  { ticker: 'T', name: 'AT&T Inc.', sector: 'Communication Services' },
  { ticker: 'VZ', name: 'Verizon Communications Inc.', sector: 'Communication Services' },
  { ticker: 'TMUS', name: 'T-Mobile US Inc.', sector: 'Communication Services' },
  { ticker: 'SBUX', name: 'Starbucks Corporation', sector: 'Consumer Cyclical' },
  { ticker: 'MCD', name: 'McDonald\'s Corporation', sector: 'Consumer Cyclical' },
  { ticker: 'LOW', name: 'Lowe\'s Companies Inc.', sector: 'Consumer Cyclical' },
  { ticker: 'TJX', name: 'The TJX Companies Inc.', sector: 'Consumer Cyclical' },
  { ticker: 'TGT', name: 'Target Corporation', sector: 'Consumer Cyclical' },
  { ticker: 'EL', name: 'The Estée Lauder Companies Inc.', sector: 'Consumer Defensive' },
  { ticker: 'CL', name: 'Colgate-Palmolive Company', sector: 'Consumer Defensive' },
  { ticker: 'MDLZ', name: 'Mondelez International Inc.', sector: 'Consumer Defensive' },
  { ticker: 'MO', name: 'Altria Group Inc.', sector: 'Consumer Defensive' },
];
